services:
  db:
    container_name: password_manager_pg
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pass-manager-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-test:
    container_name: password_manager_pg_test
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env.test
    volumes:
      - pass-manager-db-test:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: password_manager_adminer
    depends_on:
      - db
      - db-test
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pass-manager-db:
  pass-manager-db-test:
